spring:
  application:
    name: meetingex

  datasource:
    url: jdbc:mysql://localhost:3306/swaggerdb
    username: giga
    password: chad
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012