spring:
  application:
    name: swaggerexam
#  security:
#    user:
#      name: admin
#      password: admin
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Iv23liE2QGPqNjRaQwLB
#            client-secret: 24cf7114f9b53011b3b79b6b32d972009ba051b7
#            scope:
#              - email
#              - profile
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: GitHub
#        provider:
#          github:
#            authorization-uri: https://github.com/login/oauth/authorize
#            token-uri: https://github.com/login/oauth/access_token
#            user-info-uri: https://api.github.com/user
#            user-name-attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/swaggerdb
    username: giga
    password: chad
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#server:
#  tomcat:
#    max-threads: 2
#    min-spare-threads: 2
#
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE



jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012